### ISSUE TITLE
Logic for removing accounts

### ISSUE THREAD

**Issue by dostuffthatmatters** [fastsurvey/authentication-backend#18]

**Comment by Alig1493** [comment]
Greetings. I was hoping to look into this issue however the documentation link in the readme seems to be outdated. Also would it be possible to get some default values for the env? Thanks

**Comment by dostuffthatmatters** [comment]
Hi @Alig1493 ,

we (fastsurvey) decided not to use a separate server for authentication. Furthermore we decided to ditch the JSON Web Token approach. This setup added a lot of complication with close to no benefit in our case.

You can check out our current backend which contains all logic (including authentication) for managing account: https://github.com/fastsurvey/backend

---

**Why not two servers:** Whenever you have a separate server, which is managing authentication only, there is the problem of having two account-records in two separate databases. This makes the creation, manipulation and deletion of user accounts (all of those operations should be atomic) unnecessarily hard.

**Why not JWTs:** The (theoretical benefit) of using JWTs is that you have account data baked into the token and that you can verify it without any db lookup. However, in practice there are many problems with this approach:
* First of all, the client libraries for JWT's do not really work and therefore we were only able to use them as plain API keys (https://github.com/fastsurvey/console/blob/e46c5c352a67220e30af9c8456c52b1a45ba3745/src/utilities/backend/authentication/login-with-cookie.ts#L42)
* Secondly if the account data (also contained in the JWT) changes, old JWTs will still be seen as valid by the backend - to fix that, the backend has to look up whether the account data is valid -> one major selling point of JWTs is gone
* Finally, what if an account is remove, or the user wants to log out from all devices, or the password is changed. There is no way of invalidating JWTs without them either expiring or having a blacklist. This blacklist is again a database table/collection which has to be looked up

---

You can find our documentation about this two-server-jwt-setup here (the current site obviously does not contain these articles anymore): https://5f994c4909d5a000087a0e38--fast-survey-docs.netlify.app/docs/authentication/api-keys-vs-oauth2

Best wishes,
Moritz

**Comment by Alig1493** [comment]
ok noted. So is the project moved now to a new repo? Because other than the env there were also a few more things that needed changing for the project to run smoothly on docker, especially testing. I also think the images could be made a lot smaller.

**Comment by dostuffthatmatters** [comment]
> ok noted. So is the project moved now to a new repo? Because other than the env there were also a few more things that needed changing for the project to run smoothly on docker, especially testing. I also think the images could be made a lot smaller.

Yes, we are not using/continuing this repository.

Sure, there is a ton missing here and it can definitely be optimized :)

**Comment by empicano** [comment]
Hey, just chiming in to give some more explanation on why we discontinued this project. As @dostuffthatmatters explained, the two major points were that **(1)** we realized that JWTs are not a good choice for user sessions and **(2)** we realized that a monolith is just _so_ much simpler to maintain in most cases. In my opinion, if you can do without microservices, do without, otherwise you're just giving yourself headaches for nothing.

I found these related blog articles interesting:

* http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/
* https://fly.io/blog/api-tokens-a-tedious-survey/
* https://www.infoq.com/news/2015/06/scaling-stack-overflow/ (StackOverflow runs on a monolith)
* https://nickcraver.com/blog/2013/11/22/what-it-takes-to-run-stack-overflow/
